
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const FETCH_WEATHER = 'FETCH_WEATHER';
export const LOADING_WEATHER = 'LOADING_WEATHER';
export const UPDATE_WEATHER = 'UPDATE_WEATHER';
export const FAIL_WEATHER = 'FAIL_WEATHER';

export const FETCH_STARWARS = 'FETCH_STARWARS';
export const LOADING_STARWARS = 'LOADING_STARWARS';
export const UPDATE_STARWARS = 'UPDATE_STARWARS';
export const FAIL_STARWARS = 'FAIL_STARWARS';
